name: boj_crawler
	
  on:
    schedule:
        # 매일 아침 9시 (한국기준)
      - cron: '0 0 * * *'
	
  # workflow는 다양한 job으로 구성되어 있으며 병렬실행 됨
  jobs:
    build:
      
      # runs-on: 어떤 os에서 실행될지
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        
        # uses: 어떤 액션을 사용할지 지정함
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run main.py
        run: |
          python main.py
        env:
          MY_GITHUB_TOKEN: # 토큰작성
